# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 22:18
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='character',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
