# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_auto_20160930_1701'),
        ('sheets', '0004_auto_20160930_1002'),
    ]

    operations = [
    ]
