# Generated by Django 1.10.1 on 2016-09-29 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0003_auto_20160927_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_hired',
        ),
    ]
